language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE cctestsdb;'
script:
  - php -v
  - phpunit --version
  - cd tests; php codecept.phar --version; cd ..
  - cd tests
  - php codecept.phar run
  - cd ..
